### ISSUE TITLE
Cannot git submodule

### ISSUE THREAD

**Issue by c4yg70** [zwbetz-gh/papercss-hugo-theme#1]
When I do this command in my git bash on Windows 10 1809:
$ git submodule add https://github.com/zwbetz-gh/papercss-hugo-theme.git themes/papercss-hugo-theme
The bash told me that:
fatal: not a git repository (or any of the parent directories): .git

**Comment by zwbetz-gh** [comment]
Hi @encofcomic, this is because your site must first be initialized as a git repo before submodules can be added. So run this first:
```
git init
```
