### ISSUE TITLE
Add Collapsibles 

### ISSUE THREAD

**Issue by h4x5p4c3** [zwbetz-gh/papercss-hugo-theme#13]
https://www.getpapercss.com/docs/components/collapsible/
it would be great if you consider to add collapsible elements

**Comment by zwbetz-gh** [comment]
Hey there.

Let me see what I can do. This will take some thought to make it work as a
shortcode. No promises.

**Comment by zwbetz-gh** [comment]
Added a `collapsible` shortcode in https://github.com/zwbetz-gh/papercss-hugo-theme/commit/cd81179a5abbe8915879b1a5c9eec58757aaad84

Checkout the demo here https://papercss-hugo-theme.netlify.app/papercss-shortcodes/#collapsible

Try it out and let me know what you think.

**Comment by h4x5p4c3** [comment]
Thanks it looks great
