### ISSUE TITLE
When using a something like domain.com/blog, the main brand image redirects to domain.com instead of domain.com/blog

### ISSUE THREAD

**Issue by mitsha-microsoft** [zwbetz-gh/papercss-hugo-theme#7]
**Is your feature request related to a problem? Please describe.**
I setup my Hugo config.toml to have a `baseURL` as https://some-domain.com/blog. The main title nav (the nav-brand) logo links to https://some-domain.com which is some weird behavior.

**Describe the solution you'd like**
Some way in the config to specify the link for the same like the other nav parameters.

**Describe alternatives you've considered**
Tried tinkering around with config but couldnt fix it from there

**Additional context**
This is the link I am talking about.
![image](https://user-images.githubusercontent.com/58204159/100705812-e3514b00-33cd-11eb-9fd3-1b07982a1425.png)

**Comment by zwbetz-gh** [comment]
The nav title link can now be set by using the `navTitleLink` param. See commit 573b3dd0be2a4af66437e03ed8b7c149d202acb1
